"""Initial migration for Neon DB

Revision ID: 32d29e1c1a74
Revises: 
Create Date: 2025-10-21 16:24:48.542018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d29e1c1a74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active_sandbox_id', sa.String(), nullable=True),
    sa.Column('sandbox_state', sa.Enum('RUNNING', 'PAUSED', 'KILLED', 'NONE', name='sandboxstate'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('project_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_tool', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'file_path', name='uq_project_file_path')
    )
    op.create_index(op.f('ix_project_files_created_at'), 'project_files', ['created_at'], unique=False)
    op.create_index('ix_project_files_deleted', 'project_files', ['project_id', 'is_deleted', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_project_files_file_path'), 'project_files', ['file_path'], unique=False)
    op.create_index(op.f('ix_project_files_is_deleted'), 'project_files', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_project_files_project_id'), 'project_files', ['project_id'], unique=False)
    op.create_index('ix_project_files_project_path', 'project_files', ['project_id', 'file_path'], unique=False)
    op.create_table('project_thoughts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('thought', sa.Text(), nullable=False),
    sa.Column('thought_type', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=True),
    sa.Column('milestone', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_thoughts_milestone'), 'project_thoughts', ['milestone'], unique=False)
    op.create_index(op.f('ix_project_thoughts_phase'), 'project_thoughts', ['phase'], unique=False)
    op.create_index(op.f('ix_project_thoughts_priority'), 'project_thoughts', ['priority'], unique=False)
    op.create_index(op.f('ix_project_thoughts_project_id'), 'project_thoughts', ['project_id'], unique=False)
    op.create_index('ix_project_thoughts_project_phase', 'project_thoughts', ['project_id', 'phase'], unique=False)
    op.create_index('ix_project_thoughts_project_type', 'project_thoughts', ['project_id', 'thought_type'], unique=False)
    op.create_index(op.f('ix_project_thoughts_timestamp'), 'project_thoughts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_thoughts_timestamp'), table_name='project_thoughts')
    op.drop_index('ix_project_thoughts_project_type', table_name='project_thoughts')
    op.drop_index('ix_project_thoughts_project_phase', table_name='project_thoughts')
    op.drop_index(op.f('ix_project_thoughts_project_id'), table_name='project_thoughts')
    op.drop_index(op.f('ix_project_thoughts_priority'), table_name='project_thoughts')
    op.drop_index(op.f('ix_project_thoughts_phase'), table_name='project_thoughts')
    op.drop_index(op.f('ix_project_thoughts_milestone'), table_name='project_thoughts')
    op.drop_table('project_thoughts')
    op.drop_index('ix_project_files_project_path', table_name='project_files')
    op.drop_index(op.f('ix_project_files_project_id'), table_name='project_files')
    op.drop_index(op.f('ix_project_files_is_deleted'), table_name='project_files')
    op.drop_index(op.f('ix_project_files_file_path'), table_name='project_files')
    op.drop_index('ix_project_files_deleted', table_name='project_files')
    op.drop_index(op.f('ix_project_files_created_at'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
